// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mstyaefjathcnaszzzki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zdHlhZWZqYXRoY25hc3p6emtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjMzMDgsImV4cCI6MjA1OTA5OTMwOH0.RccMsJNf1sIKE2E07b8P855aFETAnjYr1jovyQvTIB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);